name: Python Learning Agent

on:
  schedule:
    - cron: '13 13 * * *'  # 7:13 AM CST (13:13 UTC)
    - cron: '18 18 * * *'  # 12:18 PM CST (18:18 UTC)
    - cron: '0 0 * * *'    # 6:00 PM CST (00:00 UTC next day)
    - cron: '5 5 * * *'    # 11:05 PM CST (05:05 UTC next day)
  workflow_dispatch:

jobs:
  run-learning-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run learning agent
        run: python learning_agent.py
